version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"  # Expose ChromaDB on 8001 to avoid conflict with API
    volumes:
      - chromadb_data:/chroma/chroma  # Persist data
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - OTEL_SERVICE_NAME=chromadb
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/heartbeat')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    container_name: multi-modal-km-agent-api
    ports:
      - "8000:8000"  # API on 8000
    # depends_on:
    #   chromadb:
    #     condition: service_healthy  # Wait for ChromaDB to be healthy
    environment:
      - VLLM_MODEL_NAME=microsoft/DialoGPT-medium
      - CLOUD_ENV=
      - CHROMA_DB_PATH=http://chromadb:8000  # Connect to ChromaDB service
    volumes:
      - ./configs:/app/configs  # Mount configs for easy editing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  chromadb_data:
    driver: local
